### ISSUE TITLE
Question: release strategy

### ISSUE THREAD

**Issue by favoyang** [needle-tools/glitch-package-installer#3]
Hi there,

I wonder what's the release strategy for the installer. Is the master branch considering stable and always deployed to the live site? Or the deployment is git-tag-based?

**Comment by hybridherbst** [comment]
Hi Favo,
since this is currently deployed on glitch it can be a bit confusing: the live version isn't necessarily tracked in this repo here (as glitch maintains a separate repo); development happens in this repo here and then a tagged version is "imported" into glitch (not ideal).

That being said, we're in the process of updating the Backend to a better format and setting up CI so we can ensure stability going forward - this work will hopefully be completed over the next weeks, and I'll also look into releasing as standalone npm package (no promises there though).

**Comment by favoyang** [comment]
Thanks for the details. Then the live version is/could be a "branch" of a tagged version. Because I deployed the installer to the China region by using a version from the master branch, I want to know the release strategy to follow. So I'm gonna watch the release tag for now.
